"""add timestamps to idea

Revision ID: 0981ee608d52
Revises: 4d7f9a23e470
Create Date: 2025-04-28 18:55:27.501512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0981ee608d52'
down_revision = '4d7f9a23e470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('createdAt',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.alter_column('createdAt',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('updatedAt')

    # ### end Alembic commands ###
