"""add short desc to idea

Revision ID: 4d7f9a23e470
Revises: 50ffd709c1e8
Create Date: 2025-04-26 14:21:09.138085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d7f9a23e470'
down_revision = '50ffd709c1e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_desc', sa.String(length=300), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.drop_column('short_desc')

    # ### end Alembic commands ###
