"""add notepad title

Revision ID: 6ae712bfa0b9
Revises: ea94ce657cff
Create Date: 2025-04-30 00:12:24.268433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ae712bfa0b9'
down_revision = 'ea94ce657cff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idea_notepads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idea_notepads', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
